// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deleteChirpyById.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChripyById = `-- name: DeleteChripyById :exec
DELETE FROM chirps WHERE id = $1
`

func (q *Queries) DeleteChripyById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChripyById, id)
	return err
}
