// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getPasswordFromEmail.sql

package database

import (
	"context"
)

const getPasswordFromEmail = `-- name: GetPasswordFromEmail :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE email = $1
`

func (q *Queries) GetPasswordFromEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getPasswordFromEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
